Myentity & CRUD operations
nicolas63/JhipsterXamarin pull request #20
Opened 2020-11-03 11:04 UTC by Zenrac

Fix: #4 #5 #11 #7

2020-11-03 13:35 UTC, nicolas63 requested changes

2020-11-03 13:35 UTC, nicolas63 commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/Services/AuthenticationService.cs
>          public UserModel CurrentUser { get; set; }
private non ?

2020-11-03 13:35 UTC, nicolas63 commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/ViewModels/ListViewModel.cs
> +            _navigationService.Navigate<LoginViewModel, HttpClient>(new HttpClient()));
il faut injecter l'http client

2020-11-03 13:35 UTC, nicolas63 commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/ViewModels/LoginViewModel.cs
> +    public class LoginViewModel : MvxViewModel<HttpClient>
MvxViewModel<HttpClient> ??? pourquoi httpclient ici

2020-11-03 13:35 UTC, nicolas63 commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/ViewModels/MyEntityViewModel.cs
> +    public class MyEntityViewModel : MvxViewModel<HttpClient>
MvxViewModel<HttpClient> ?

2020-11-03 13:35 UTC, nicolas63 commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/ViewModels/MyEntityViewModel.cs
> +            _myEntityService = new MyEntityService(_httpClient);
il faut utiliser l'injection ici plutôt qu'une création manuel

2020-11-03 13:41 UTC, Zenrac commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/ViewModels/ListViewModel.cs
> +            _navigationService.Navigate<LoginViewModel, HttpClient>(new HttpClient()));
Modifié dans les derniers commits

2020-11-03 13:41 UTC, Zenrac commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/ViewModels/LoginViewModel.cs
> +    public class LoginViewModel : MvxViewModel<HttpClient>
Modifié dans les derniers commits

2020-11-03 13:41 UTC, Zenrac commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/ViewModels/MyEntityViewModel.cs
> +    public class MyEntityViewModel : MvxViewModel<HttpClient>
Modifié dans les derniers commits également

2020-11-03 13:41 UTC, Zenrac commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/ViewModels/MyEntityViewModel.cs
> +            _myEntityService = new MyEntityService(_httpClient);
Modifié dans les derniers commits aussi

2020-11-03 13:42 UTC, Zenrac commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/Services/AuthenticationService.cs
>          public UserModel CurrentUser { get; set; }
Modifié dans le dernier commit

2020-11-03 14:03 UTC, nicolas63 requested changes

2020-11-03 14:03 UTC, nicolas63 commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/Services/AuthenticationService.cs
> +        private JwtToken JwtToken { get; set; }
attention à l'ordre il faut mettre les `private` puis les `public`

2020-11-03 14:03 UTC, nicolas63 commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/ViewModels/MyEntityViewModel.cs
> +        private List<MyEntityModel> _listElement;
ici même chose pour l'ordre en haut les attributs private puis les propriétés

2020-11-03 14:03 UTC, nicolas63 commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/ViewModels/MyEntityViewModel.cs
> +        private List<MyEntityModel> _listElement;
https://google.github.io/styleguide/csharp-style.html

2020-11-03 16:39 UTC, nicolas63 requested changes

2020-11-03 16:39 UTC, nicolas63 commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/ViewModels/MyEntityViewModel.cs
> +        public IMvxCommand AddCommand { get; }
les propriétés avant le constructeur

2020-11-03 16:41 UTC, nicolas63 commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/ViewModels/MyEntityViewModel.cs
> +            _myEntityService = new MyEntityService(_httpClient);
si le client http est enregistré alors votre service sera bien injecté avec le client http

2020-11-04 08:22 UTC, Zenrac commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/ViewModels/MyEntityViewModel.cs
> +            _myEntityService = new MyEntityService(_httpClient);
Résolu par le commit [994bd7](https://github.com/nicolas63/JhipsterXamarin/pull/20/commits/994bd70e88cb1b1ebf16140ba9b13fe3df78942a).

2020-11-04 08:22 UTC, Zenrac commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/ViewModels/MyEntityViewModel.cs
> +        public IMvxCommand AddCommand { get; }
Résolu par le commit [994bd7](https://github.com/nicolas63/JhipsterXamarin/pull/20/commits/994bd70e88cb1b1ebf16140ba9b13fe3df78942a).

2020-11-04 08:28 UTC, nicolas63 approved these changes

2020-11-04 11:18 UTC, merged