Added Unit Test
nicolas63/JhipsterXamarin pull request #26
Opened 2020-11-06 16:48 UTC by Thomas-Julien-SAHUT

2020-11-06 21:26 UTC, nicolas63 requested changes

2020-11-06 21:26 UTC, nicolas63 commented on JhipsterXamarin/UnitTestJhispterXamarin/packages.config
> +  <package id="System.Net.Http" version="4.3.4" targetFramework="net472" />
To resolve you problem you need to add 
  `<package id="System.Net.Http.Json" version="3.2.1" targetFramework="net472" /> `
here

2020-11-06 21:26 UTC, nicolas63 commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/Services/AuthenticationService.cs
> +        public HttpClient _httpClient { get; set; }
Can you revert this change ? You don't need to expose http client

2020-11-06 21:26 UTC, nicolas63 commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/Services/IAuthenticationService.cs
> +        HttpClient _httpClient { get; set; }
Can you revert this change too ?

2020-11-12 19:28 UTC, nicolas63 requested changes

2020-11-12 19:28 UTC, nicolas63 commented on JhipsterXamarin/UnitTestJhispterXamarin/TestLogin.cs
> +            initializeAll();
you must use [TestInitiliaze] or [ClassInitialize] => https://www.automatetheplanet.com/mstest-cheat-sheet/

2020-11-12 19:28 UTC, nicolas63 commented on JhipsterXamarin/UnitTestJhispterXamarin/TestLogin.cs
> +            Assert.AreEqual(loginViewModel.GetAuthenticationService().SignIn(loginModel).ToString(), loginViewModel.SignInConnection().ToString(), "Test failed : login error user : admin  | password
replace this assertion and use fluent assertion

2020-11-12 19:28 UTC, nicolas63 commented on JhipsterXamarin/UnitTestJhispterXamarin/TestService.cs
> +            Assert.AreEqual(expected, result.Name, "Test failed: We wanted : " + expected + " We have :  " +result.Name);
use fluent assertion

2020-11-15 12:44 UTC, nicolas63 commented
this code does not compile ! Can you fix it ?

2020-11-15 15:43 UTC, Thomas-Julien-SAHUT commented
I update UT to solve 1 issue on UT but I still have this issue : The Initialization UnitTestJhispterXamarin.TestService.TestViewModel method threw an exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http.Json, Version = 3.2.0.0, Culture = neutral, PublicKeyToken = cc7b13ffcd2ddd51' or one of its dependencies. The specified file can not be found..

2020-11-23 16:16 UTC, Thomas-Julien-SAHUT commented
UserEntityViewModelTest doesn't work now: issue on the UserEntityViewModelTest.Initialize about Castle.DynamicProxy.InvalidProxyConstructorArgumentsException: Can not instantiate proxy of class: JhipsterXamarin.Services.UserEntityService`1[[JhipsterXamarin.Models.UserModel, JhipsterXamarin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].

2020-11-26 16:29 UTC, Thomas-Julien-SAHUT commented
Unit Test Are good for a review now.

2020-11-28 08:48 UTC, nicolas63 requested changes

2020-11-28 08:48 UTC, nicolas63 commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/Utilities/ActionResultExtensions.cs
> +    public static class ActionResultExtensions
To be deleted

2020-11-28 08:48 UTC, nicolas63 commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/Utilities/ActionResultUtil.cs
> +        public static ActionResult WrapOrNotFoundAsDto<TDtoType>(object value, IMapper mapper)
To be deleted

2020-11-28 08:48 UTC, nicolas63 commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/Utilities/ActionResultWithHeaders.cs
> +        public class ActionResultWithHeaders : ActionResult {
To be deleted

2020-11-28 08:48 UTC, nicolas63 commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/Utilities/HeaderUtil.cs
> +    public static class HeaderUtil
To be deleted

2020-11-28 08:48 UTC, nicolas63 commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/ViewModels/UserEntityViewModel.cs
> +    public class UserEntityViewModel : MvxViewModel
why this code is in this PR  ?

2020-11-28 08:48 UTC, nicolas63 commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/Views/UserEntityView.xaml
> +<views:MvxContentPage xmlns:views="clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms"
why this code is in this PR

2020-11-28 08:48 UTC, nicolas63 commented on JhipsterXamarin/UnitTestJhispterXamarin/Tests/LoginTest.cs
> +        }
add a line break

2020-11-28 08:48 UTC, nicolas63 commented on JhipsterXamarin/UnitTestJhispterXamarin/Tests/MyEntityViewModelTest.cs
> +        }
add a line break

2020-11-28 08:48 UTC, nicolas63 commented on JhipsterXamarin/UnitTestJhispterXamarin/Tests/MyEntityViewModelTest.cs
> +            myThirdEntityModelSimple.Age = 3;
Can you use AutoFixture to generate this entities ?

2020-11-28 08:50 UTC, nicolas63 requested changes

2020-11-28 08:50 UTC, nicolas63 commented on JhipsterXamarin/UnitTestJhispterXamarin/Tests/UserEntityViewModelTest.cs
> +            admin.Id = "admin";
This do not compile. Can you fix it ? We also need to add UT in build step of the github action

2020-11-28 08:54 UTC, nicolas63 commented
The actual coverage on the tested view model is close to 60%. we need to get 80%.

2020-11-28 08:56 UTC, nicolas63 requested changes

2020-11-28 08:56 UTC, nicolas63 commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/Logs.cs
> +    public static class Logs
To be deleted

2020-11-28 08:56 UTC, nicolas63 commented on JhipsterXamarin/JhipsterXamarin/JhipsterXamarin/Constants/ErrorConstants.cs
> +    public static class ErrorConstants
Merge conflict ? This class is already in shared project

2020-12-04 07:56 UTC, nicolas63 approved these changes

2020-12-05 00:42 UTC, merged